language: c
sudo: false
env:
  global:
  - secure: "HxnRtl6pMc+nbszQgDgvMuroMG5AuviULPb0MxPfEIZqYSwKALgc0ILXc89kJyf9rFfpsUdKGmtrGOytzXIp8Yuxvp+fnk/rtuuRyMLeWA0sJ75/Jn+l0BKVid6LNwl7bA4aMOSkjL85kaxU2e5HtlROUkiAgmdAcV10BoK7Vh7yC/S4Zl3kzyCQd8AGSxk0AbeQrb9vK7T1+gWVkEjUFtUsFJ3q5SGrO/j3825qLoRnYj/bKUgtYExQNKjTnTYMbeok+mKJEO1VbLeTk1ri8bLyO2x25lhGImaJSgdPOzuH905ALrf+EHkKm/FYvy5w+zERiuidwwFK5OqVOVWsD5W0G5rYKmDKpzSd39FNnrvb2Tzl2kCin70j6SDOXyZ+4k/iGJpBnOtx3+Ez4gsBDWLIba1c5EXvzhvPoycddgSLBY2LNz4EJI+YqbBTBxG7dVr4NmKKjPowFerVMLM10SgkH9ZZjbAVMxejUJTzp/4gxTanlWm/xds5uC0E0mraLY1H1yzGtwij/lVJN8RGbuhvW9jluLYQzfN7Hb/MReBXTKwdVo5SnsZzv9GEM56IsQXgIhzRoHAuDHd8rS1rfXGaOVfsbYK7pBjtx9j+Pq3BNSPlIL5u4j2JXH6QVJSNaK1npCq81S21dIBfYTP49ft28bhgVE0czkD7kl3fCCk="

cache:
  directories:
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - export OLEAN_RS=https://github.com/cipher1024/olean-rs/releases
  - export latest=$(curl -sSf "$OLEAN_RS/latest" | cut -d'"' -f2 | awk -F/ '{print $NF}')
  - curl -sSfL "$OLEAN_RS/download/$latest/olean-rs-linux" -o "$HOME/scripts/olean-rs"
  - chmod +x $HOME/scripts/olean-rs
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long
  - git clean -d -f -q
  - export LEAN_VERSION=lean-`lean --run scripts/lean_version.lean`

jobs:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
      os:
        - linux
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - pip3 install .
        - update-mathlib
        - cache-olean
        - yes | setup-lean-git-hooks

    - language: sh
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
      os:
        - osx
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - pip3 install .
        - update-mathlib
        - cache-olean
        - yes | setup-lean-git-hooks

    - sudo: true
      language: python
      python:
        - "3.5"
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
      os:
        - linux
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - pip3 install .
        - cd scripts
        - update-mathlib
        - cache-olean
        - cache-olean --fetch
        - yes | setup-lean-git-hooks

    - language: sh
      install:
        - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
      os:
        - osx
      script:
        - cp scripts/leanpkg-example.toml leanpkg.toml
        - pip3 install .
        - cd scripts
        - update-mathlib
        - cache-olean
        - cache-olean --fetch
        - yes | setup-lean-git-hooks
