version: 1.0.{build}
build: off
# only_commits:
#   files:
#     - scripts/*
#     - appveyor.yml

environment:
  GITHUB_CRED:
    secure: RPr/nQN2GbjWFfbUiBzpVeO/ojQYoAeqHjOAUhvzHk3DnrbY72zR6yUQQ8AETGtG
  matrix:
    - PYTHON: "Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    - PYTHON: "Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

test_script:
    - sh -c "if [ '%GITHUB_CRED%' != '' ]; then git config --add github.oauthtoken %GITHUB_CRED%; echo setting up GitHub credentials; else echo no GitHub credentials available; fi"
    - "SET PATH=C:\\Users\\appveyor\\AppData\\Roaming\\Python\\%PYTHON%\\Scripts;C:\\%PYTHON%;C:\\%PYTHON%\\Scripts; %PATH%"
    - sh -c "echo export PATH=\\\"/c/Users/appveyor/AppData/Roaming/Python/%PYTHON%/Scripts:/c/%PYTHON%:/c/%PYTHON%/Scripts:\$PATH\\\" >> $HOME/.profile"
    - "python --version"
    - cp scripts/leanpkg-example.toml leanpkg.toml
    - sh -c "ln -s `which python` `which python`3"
    - sh -c "pip3 install ."
    - sh -c "source $HOME/.profile; update-mathlib"
    - sh -c "source $HOME/.profile; yes | setup-lean-git-hooks"
    - sh -c "source $HOME/.profile; cache-olean"

    # what if it's already installed?
    - sh -c "pip3 install ."
    - sh -c "source $HOME/.profile; update-mathlib"
    - sh -c "source $HOME/.profile; yes | setup-lean-git-hooks"
    - sh -c "source $HOME/.profile; cache-olean"

    - sh -c "pip3 install ."
    - sh -c "source $HOME/.profile; update-mathlib"
    - sh -c "source $HOME/.profile; cache-olean"
    - sh -c "source $HOME/.profile; cache-olean --fetch"
    - sh -c "source $HOME/.profile; yes | setup-lean-git-hooks"
    # do it again
    - sh -c "pip3 install ."
    - sh -c "source $HOME/.profile; update-mathlib"
    - sh -c "source $HOME/.profile; cache-olean"
    - sh -c "source $HOME/.profile; cache-olean --fetch"
    - sh -c "source $HOME/.profile; yes | setup-lean-git-hooks"
